version: "2.2"

services:
  elasticsearch:
    build: ./deps/elasticsearch/
    volumes:
      - ./data/elasticsearch-data:/usr/share/elasticsearch/data
      - ./data/elasticsearch-log:/var/log
    ports:
      - "127.0.0.1:9200:9200"
    expose: [9200]
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "cluster.routing.allocation.disk.watermark.low=3gb"
      - "cluster.routing.allocation.disk.watermark.high=2gb"
      - "cluster.routing.allocation.disk.watermark.flood_stage=1gb"

  app:
    build: .
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    links:
      - elasticsearch
    volumes:
      - "./:/code"
    environment:
      SHELL: /bin/bash
      OG_ELASTICSEARCH_URI: http://elasticsearch:9200
    ports:
      - "127.0.0.1:8000:8000"

volumes:
  elasticsearch-data: {}
  elasticsearch-log: {}
